name: Build EnhancedUnrealEngineDocumentation
on:
  push:
    paths-ignore:
      - README.md
      - CHANGELOG.md
  pull_request:
    paths-ignore:
      - README.md
      - CHANGELOG.md
  workflow_dispatch:
    inputs:
      arguments:
        description: 'Additional attributes to gradle buildPlugin'
        required: false
        default: ''
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - { name: "Windows Latest", artifact-prefix: "EnhancedUnrealEngineDocumentation-",
            os: windows-latest,
            SEP: \ }

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2 # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build Plugin
        run: gradlew.bat buildPlugin -PbuildCounter=${{ github.run_number }} -PbuildConfiguration=Release ${{ github.event.inputs.arguments }}
        shell: cmd

      - name: Upload artifacts
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.artifact-prefix }}artifacts
          path: output/**
